#!/bin/sh
regex='@users\.noreply\.github\.com$'
email=$GIT_AUTHOR_EMAIL

if [[ $email =~ $regex ]]
then
    echo Your email $email satisfies Git policy
    exit 0
else
    echo Your email $email does not satisfy Git policy
fi